### ISSUE TITLE
.DS_Store problems

### ISSUE THREAD

**Issue by ard1209** [soc504-s2015-princeton/slides#2]
Somehow I ran into a merge conflict with this file. I think I've restored it what it looked like before I made this serious of commits that changed it. I'm not sure what exactly this file is doing, but if this was set to do something specific, it would be good for someone to review it.

**Comment by msalganik** [comment]
The .DS_Store file is something that has to do with how Macs display the files. We don't need to worry about syncing that file.

I've pulled your most recent changes and everything looks good to me.  Therefore, I'm closing this issue.
